spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: h2
  datasource:
    url:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

password-reset:
  url: http://localhost:8080/profile/resetPassword

content-path:
  documents: ./content/documents/
  change-notices: ./content/change-notices/

search-results-limit: 7
