spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 465
    username: niemi.filecabinet@gmail.com
    password: jdarcyyrnysveblq
    protocol: smtps

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

password-reset:
  token-expiration-time: 86400000
  url: https://javaprojects.ru/archivist/profile/resetPassword
