spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  sql:
    init:
      mode: always
      encoding: UTF-8
#  datasource:
#    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
