spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/archivist
    username: user
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 465
    username: javaprojects.test@gmail.com
    password: puqtlmwroiyfcwrv
    protocol: smtps
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

password-reset:
  token-expiration-time: 86400000
  url: https://javaprojects.ru/archivist/profile/resetPassword

content-path:
  documents: ./content/documents/
  change-notices: ./content/change-notices/

search-results-limit: 50

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: logs/archivist.log
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%mdc]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}'
    file: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%mdc]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}'
