package ru.javaprojects.archivist.changenotices.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.transaction.annotation.Transactional;
import ru.javaprojects.archivist.changenotices.model.ChangeNotice;
import ru.javaprojects.archivist.common.NamedRepository;

import java.util.Optional;

@Transactional(readOnly = true)
public interface ChangeNoticeRepository extends NamedRepository<ChangeNotice> {

    Page<ChangeNotice> findAllByAutoGeneratedIsFalseOrderByName(Pageable pageable);

    Page<ChangeNotice> findAllByNameContainsIgnoreCaseAndAutoGeneratedIsFalseOrderByName(Pageable pageable, String keyword);

    @EntityGraph(attributePaths = {"developer", "changes.document"})
    Optional<ChangeNotice> findWithChangesAndDeveloperByIdAndAutoGeneratedIsFalse(long id);

    @EntityGraph(attributePaths = {"developer", "changes.document"})
    Optional<ChangeNotice> findWithChangesAndDeveloperByName(String name);


    @EntityGraph(attributePaths = "changes.document")
    Optional<ChangeNotice> findWithChangesById(long id);

    Optional<ChangeNotice> findByNameIgnoreCaseAndAutoGeneratedIsTrue(String name);

    @Transactional
    @Modifying
    @Query("DELETE FROM ChangeNotice c WHERE UPPER(c.name) =UPPER(:name) AND c.autoGenerated = TRUE")
    void deleteByNameIgnoreCaseAndAutoGeneratedIsTrue(String name);

    @EntityGraph(attributePaths = "changes")
    Optional<ChangeNotice> findWithChangesByNameIgnoreCase(String name);
}
