package ru.javaprojects.archivist.changenotices;

import jakarta.validation.Valid;
import jakarta.validation.groups.Default;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;
import org.springframework.validation.annotation.Validated;
import ru.javaprojects.archivist.changenotices.model.Change;
import ru.javaprojects.archivist.changenotices.model.ChangeNotice;
import ru.javaprojects.archivist.changenotices.repository.ChangeNoticeRepository;
import ru.javaprojects.archivist.changenotices.repository.ChangeRepository;
import ru.javaprojects.archivist.changenotices.to.ChangeNoticeTo;
import ru.javaprojects.archivist.common.error.IllegalRequestDataException;
import ru.javaprojects.archivist.common.error.NotFoundException;
import ru.javaprojects.archivist.common.util.FileUtil;
import ru.javaprojects.archivist.common.util.validation.NotAutoGenerated;

import java.util.List;

@Service
@RequiredArgsConstructor
@Validated({NotAutoGenerated.class, Default.class})
public class ChangeNoticeService {
    private final ChangeNoticeRepository repository;
    private final ChangeRepository changeRepository;

    @Value("${content-path.change-notices}")
    private String contentPath;

    public Page<ChangeNotice> getAll(Pageable pageable) {
        return repository.findAllByAutoGeneratedIsFalseOrderByName(pageable);
    }

    public Page<ChangeNotice> getAll(Pageable pageable, String keyword) {
        return repository.findAllByNameContainsIgnoreCaseAndAutoGeneratedIsFalseOrderByName(pageable, keyword);
    }

    @Transactional
    public ChangeNotice create(@Valid ChangeNoticeTo changeNoticeTo) {
        Assert.notNull(changeNoticeTo, "changeNoticeTo must not be null");
        if (changeNoticeTo.getFile() == null) {
            throw new IllegalRequestDataException("Change notice file is not present");
        }
        ChangeNotice changeNotice = repository.findByNameAndAutoGeneratedIsTrueIgnoreCase(changeNoticeTo.getName())
                .orElseGet(() -> ChangeNoticeUtil.createNewFromTo(changeNoticeTo));
        if (!changeNotice.isNew()) {
            if (!changeNotice.getReleaseDate().equals(changeNoticeTo.getReleaseDate())) {
                throw new IllegalRequestDataException("Autogenerated change notice has different release date");
            }
            ChangeNoticeUtil.updateFromTo(changeNotice, changeNoticeTo);
        }
        repository.saveAndFlush(changeNotice);
        String fileName = changeNoticeTo.getFile().getOriginalFilename();
        FileUtil.upload(changeNoticeTo.getFile(), contentPath + changeNoticeTo.getName() + "/", fileName);
        return changeNotice;
    }

    @Transactional
    public ChangeNotice update(@Valid ChangeNoticeTo changeNoticeTo) {
        Assert.notNull(changeNoticeTo, "changeNoticeTo must not be null");
        ChangeNotice changeNotice = repository.getExisted(changeNoticeTo.getId());
        String oldFileLink = changeNotice.getFile().getFileLink();
        repository.saveAndFlush(ChangeNoticeUtil.updateFromTo(changeNotice, changeNoticeTo));
        if (changeNoticeTo.getFile() != null) {
            FileUtil.delete(contentPath + oldFileLink);
            String fileName = changeNoticeTo.getFile().getOriginalFilename();
            FileUtil.upload(changeNoticeTo.getFile(), contentPath + changeNoticeTo.getName() + "/", fileName);
        }
        return changeNotice;
    }

    public ChangeNotice get(long id) {
        return repository.findById(id).orElseThrow(() -> new NotFoundException("Entity with id=" + id + " not found"));
    }

    public List<Change> getChanges(long id) {
        return changeRepository.findAllByChangeNotice(id);
    }
}
